### ISSUE TITLE
Multiplayer Mod Desyncs Caused by UnityEngine.Random

### ISSUE THREAD

**Issue by Yolopanther12** [emipa606/MountainMiner#3]
See referenced line of code: https://github.com/emipa606/MountainMiner/blob/0f6cd269db30ae9526a1eb5627b4d4f9bf77a51b/Source/MountainMiner/Building_MountainDrill.cs#L42

Current implementation uses `UnityEngine.Random.Range` which will always desync multiplayer clients. Changing to `Verse.Rand.Range`  will otherwise allow this mod to work seamlessly with multiplayer.

[Multiplayer Mod (Steam Workshop)](https://steamcommunity.com/sharedfiles/filedetails/?id=2606448745)

**Comment by emipa606** [comment]
Should be added in 3794508
Thanks!
